### PR TITLE
Add symbolic icon

### LINKED ISSUE #23: Icon?
Every app needs an icon, so icon?

- [ ] App icon
- [x] symbolic icon #24

### PR DESCRIPTION
**Pull request by yavko**
Adds a symbolic icon
semi fixes #23

### CODE REVIEW

**Comment by yavko** [comment]
I came up with the idea of a ribbon because its note "worthy", so I thought a ribbon could signify worthiness I guess. This is one of my first icons, I'm not great with graphic design.

**Comment by SeaDve** [comment]
Thanks! looking good

**Comment by yavko** [comment]
> Thanks! It kinda looks stretched on the preview. Other than that, looking good

Weird, maybe its because its not 1:1, but most symbolic icons aren't anyways?

**Comment by SeaDve** [comment]
I think it should have 1:1 ratio. App Icon Preview from flathub may be helpful as a guide for size. It has a template that can be opened with SVG editor like inkscape, plus a preview

**Comment by yavko** [comment]
> I think it should have 1:1 ratio. App Icon Preview from flathub may be helpful as a guide for size. It has a template that can be opened with SVG editor like inkscape, plus a preview

I looked at the symbolic icons in adwaita and they seem to be scaled to the icons borders, but idk.

**Comment by yavko** [comment]
I'll make a commit with the icon as 1:1 anyways though

**Comment by yavko** [comment]
Fixed the icon!

**Comment by SeaDve** [comment]
Thanks! sorry for the very late reply. Merged.

**Comment by yavko** [comment]
> Thanks! sorry for the very late reply. Merged.

Oh, no problem, are you planning on continuing development?

**Comment by SeaDve** [comment]
Nope, unfortunately, not any time soon

**Pull request merged**
